// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function make(initialValue) {
  return initialValue;
}

function update(t, step) {
  return t + step | 0;
}

function currentValue(t) {
  return t;
}

var Counter = {
  make: make,
  update: update,
  currentValue: currentValue
};

function make$1(t) {
  return t;
}

function renderHTML(t, element, getInnerHTML, getCssClassName) {
  element.innerHTML = Curry._1(getInnerHTML, t);
  element.className = Curry._1(getCssClassName, t);
  
}

var CounterView = {
  make: make$1,
  renderHTML: renderHTML
};

var count = {
  contents: 0
};

var element = document.getElementById("count");

function renderView(count) {
  var getCssClassName = function (n) {
    if (n === 0) {
      return "count count-zero";
    } else if (n > 0) {
      return "count count-positive";
    } else {
      return "count count-negative";
    }
  };
  var getInnerHTML = function (n) {
    return "Count is " + String(n);
  };
  return renderHTML(count.contents, element, getInnerHTML, getCssClassName);
}

renderView(count);

function updateCount(count, step) {
  count.contents = count.contents + step | 0;
  
}

var plusOneButton = document.getElementById("plus-one");

plusOneButton.addEventListener("click", (function (_mouseEvt) {
        updateCount(count, 1);
        return renderView(count);
      }));

var minusOneButton = document.getElementById("minus-one");

minusOneButton.addEventListener("click", (function (_mouseEvt) {
        updateCount(count, -1);
        return renderView(count);
      }));

export {
  Counter ,
  CounterView ,
  count ,
  element ,
  renderView ,
  updateCount ,
  plusOneButton ,
  minusOneButton ,
  
}
/* element Not a pure module */
