// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function PostView(Props) {
  var post = Props.post;
  var handleDeleteLater = Props.handleDeleteLater;
  var paragraphs = Belt_Array.reduce(post.text, React.createElement(React.Fragment, undefined), (function (acc, text) {
          return React.createElement(React.Fragment, undefined, acc, React.createElement("p", {
                          className: "mb-1 text-sm"
                        }, text));
        }));
  return React.createElement("div", {
              className: "bg-green-700 hover:bg-green-900 text-gray-300 hover:text-gray-100 px-8 py-4 mb-4"
            }, React.createElement("h2", {
                  className: "text-2xl mb-1"
                }, post.title), React.createElement("h3", {
                  className: "mb-4"
                }, post.author), paragraphs, React.createElement("button", {
                  className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4",
                  onClick: Curry._1(handleDeleteLater, post)
                }, "Remove this post"));
}

var make = PostView;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
